export const SAVE_INTRO_SCREEN_DATA = 'SAVE_INTRO_SCREEN_DATA';
export const SAVE_START_SCREEN_DATA = 'SAVE_START_SCREEN_DATA';
export const SAVE_DESTINATION_SCREEN_DATA = 'SAVE_DESTINATION_SCREEN_DATA';
export const SAVE_BASIC_INFO_SCREEN_DATA = 'SAVE_BASIC_INFO_SCREEN_DATA';
export const SAVE_CONTACT_INFO_SCREEN_DATA = 'SAVE_CONTACT_INFO_SCREEN_DATA';
export const SAVE_PASSENGERS_INFO_SCREEN_DATA = 'SAVE_PASSENGERS_INFO_SCREEN_DATA';
